import React from 'react';
import CodeSnippet from '../CodeSnippet';

const FirstBlog = () => {
  return (
    <>
      <h1>Blog title</h1>
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit, mi vel eleifend sollicitudin, odio justo congue sapien, sit amet luctus orci neque nec nunc. Morbi quis euismod leo. Quisque eleifend diam et odio sagittis pretium. Nunc eget malesuada eros. Vestibulum dignissim magna eget eleifend blandit. Phasellus suscipit ut orci a mattis. Duis eget aliquet eros. Maecenas tristique id urna sit amet bibendum. Maecenas eu ipsum nec enim semper malesuada ac non odio. Nullam sed lobortis quam. Phasellus fermentum libero non orci iaculis, non interdum justo vestibulum. Donec quis tortor risus. Cras a dui vel nibh molestie consequat.
          Sed ut urna aliquet, iaculis felis et, hendrerit turpis. Maecenas posuere eleifend diam, non aliquam mi tincidunt at. Proin eu sollicitudin lectus. Praesent aliquam velit et metus pharetra molestie sit amet condimentum lacus. Praesent tortor ex, scelerisque sed aliquam vel, elementum sed dui. Phasellus nisl tortor, consequat vitae arcu a, bibendum pellentesque nunc. Fusce ac aliquet nunc. Duis semper nulla eu massa dictum, non sagittis tellus ullamcorper. In sed sem et nibh fringilla porta. Aenean at lectus vulputate, maximus dui a, varius massa. Fusce dictum, nunc sed suscipit laoreet, sapien ex scelerisque sapien, vel efficitur massa urna eget ligula. Sed ut mollis ante. Sed auctor, ligula sed lacinia dapibus, odio urna porta lacus, eu cursus ligula erat in turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent sed tincidunt nisl. Nullam pharetra ligula eu lectus congue euismod dapibus non felis.
          Vestibulum tincidunt ut mauris ac euismod. Curabitur eu enim eros. Cras a tincidunt sem. Suspendisse in dapibus est. Etiam id tristique augue. Maecenas diam felis, condimentum vitae pretium eu, tempus non lorem. Sed egestas diam ex, ac aliquam neque feugiat a. Donec libero elit, congue a magna vitae, facilisis congue turpis. Pellentesque at nisi non magna interdum vestibulum. Curabitur pharetra nulla felis, vitae molestie sem interdum a. In eget bibendum diam. Curabitur tristique augue tellus, vel malesuada felis dictum non. In hac habitasse platea dictumst.
          Vivamus sodales viverra aliquet. Ut pharetra ornare tortor. Duis at sodales enim, eget posuere lorem. Integer molestie sapien justo, ac faucibus nulla porta vitae. Fusce blandit tortor eu dictum dictum. Nunc placerat diam eget neque facilisis mollis. Suspendisse eget porttitor sem, eu sodales justo. Curabitur vitae augue erat. Nam eget lorem non sapien luctus dictum quis ullamcorper enim. Pellentesque ut auctor ligula.
          Pellentesque a diam eget nunc vehicula pharetra. Donec sed facilisis mauris. Mauris sed consectetur ipsum, at semper velit. Mauris facilisis non justo id ornare. Pellentesque est tortor, dapibus quis urna non, sagittis tincidunt turpis. In vitae erat sollicitudin, luctus orci dignissim, ultricies tortor. Pellentesque a purus ac magna lacinia fermentum non eget neque. Duis lacinia libero ut blandit eleifend. Aliquam in lectus aliquam eros luctus lacinia in vitae mi. Fusce id velit quam.
       </p>
      <CodeSnippet />
      <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus blandit, mi vel eleifend sollicitudin, odio justo congue sapien, sit amet luctus orci neque nec nunc. Morbi quis euismod leo. Quisque eleifend diam et odio sagittis pretium. Nunc eget malesuada eros. Vestibulum dignissim magna eget eleifend blandit. Phasellus suscipit ut orci a mattis. Duis eget aliquet eros. Maecenas tristique id urna sit amet bibendum. Maecenas eu ipsum nec enim semper malesuada ac non odio. Nullam sed lobortis quam. Phasellus fermentum libero non orci iaculis, non interdum justo vestibulum. Donec quis tortor risus. Cras a dui vel nibh molestie consequat.
          Sed ut urna aliquet, iaculis felis et, hendrerit turpis. Maecenas posuere eleifend diam, non aliquam mi tincidunt at. Proin eu sollicitudin lectus. Praesent aliquam velit et metus pharetra molestie sit amet condimentum lacus. Praesent tortor ex, scelerisque sed aliquam vel, elementum sed dui. Phasellus nisl tortor, consequat vitae arcu a, bibendum pellentesque nunc. Fusce ac aliquet nunc. Duis semper nulla eu massa dictum, non sagittis tellus ullamcorper. In sed sem et nibh fringilla porta. Aenean at lectus vulputate, maximus dui a, varius massa. Fusce dictum, nunc sed suscipit laoreet, sapien ex scelerisque sapien, vel efficitur massa urna eget ligula. Sed ut mollis ante. Sed auctor, ligula sed lacinia dapibus, odio urna porta lacus, eu cursus ligula erat in turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent sed tincidunt nisl. Nullam pharetra ligula eu lectus congue euismod dapibus non felis.
          Vestibulum tincidunt ut mauris ac euismod. Curabitur eu enim eros. Cras a tincidunt sem. Suspendisse in dapibus est. Etiam id tristique augue. Maecenas diam felis, condimentum vitae pretium eu, tempus non lorem. Sed egestas diam ex, ac aliquam neque feugiat a. Donec libero elit, congue a magna vitae, facilisis congue turpis. Pellentesque at nisi non magna interdum vestibulum. Curabitur pharetra nulla felis, vitae molestie sem interdum a. In eget bibendum diam. Curabitur tristique augue tellus, vel malesuada felis dictum non. In hac habitasse platea dictumst.
          Vivamus sodales viverra aliquet. Ut pharetra ornare tortor. Duis at sodales enim, eget posuere lorem. Integer molestie sapien justo, ac faucibus nulla porta vitae. Fusce blandit tortor eu dictum dictum. Nunc placerat diam eget neque facilisis mollis. Suspendisse eget porttitor sem, eu sodales justo. Curabitur vitae augue erat. Nam eget lorem non sapien luctus dictum quis ullamcorper enim. Pellentesque ut auctor ligula.
          Pellentesque a diam eget nunc vehicula pharetra. Donec sed facilisis mauris. Mauris sed consectetur ipsum, at semper velit. Mauris facilisis non justo id ornare. Pellentesque est tortor, dapibus quis urna non, sagittis tincidunt turpis. In vitae erat sollicitudin, luctus orci dignissim, ultricies tortor. Pellentesque a purus ac magna lacinia fermentum non eget neque. Duis lacinia libero ut blandit eleifend. Aliquam in lectus aliquam eros luctus lacinia in vitae mi. Fusce id velit quam.
        </p>
    </>
  );
};

export default FirstBlog;